from __future__ import annotations

from new_music_builder.domain.models import ExportPlan, PlannedMediaRow, PlannedSide, PlannedTrack, ProjectConfig
from new_music_builder.platform.i18n import t

NEW_MUSIC_WORKSHOP_URL = "https://steamcommunity.com/sharedfiles/filedetails/?id=3739256725"
NEW_MUSIC_WORKSHOP_IMAGE = "https://images.steamusercontent.com/ugc/11030006687843634655/D41A026AB76E264A5BDA091F326BFDA74041A401/?imw=268&imh=268&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true"
NEW_MUSIC_BUILDER_WORKSHOP_URL = "https://steamcommunity.com/sharedfiles/filedetails/?id=3750003838"
NEW_MUSIC_BUILDER_WORKSHOP_IMAGE = "https://images.steamusercontent.com/ugc/10075766136295686800/382CF43D2EAD857CD95D5F170DE94F741FFAA305/?imw=268&imh=268&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true"
WORKSHOP_TOTAL_CHAR_BUDGET = 7400
WORKSHOP_MIN_TRACK_ROWS_PER_TABLE = 3
WORKSHOP_TAIL_LINES = [
    "tags=Build 42;Audio",
    "visibility=public",
    "",
]


def build_workshop_txt_lines(project: ProjectConfig, plan: ExportPlan) -> list[str]:
    mod_name = _escape_workshop_text((project.mod_name or "").strip())
    mixed_modes = _has_mixed_modes(plan)
    lines = [
        "version=1",
        "id=",
        f"title={mod_name}",
        f"description=[h2]{mod_name}[/h2]",
        "description=",
        *_render_support_table(),
        "description=",
    ]

    lines.extend(_render_mode_legend(plan))

    first_table = True
    for title, sections in _ordered_workshop_tables(project, plan, mixed_modes=mixed_modes):
        for label, tracks in sections:
            if not first_table:
                lines.append("description=")
            lines.extend(
                _render_track_table(
                    title,
                    label,
                    tracks,
                    current_chars=_line_char_count(lines),
                    reserved_chars=_line_char_count(WORKSHOP_TAIL_LINES),
                )
            )
            first_table = False

    lines.extend(WORKSHOP_TAIL_LINES)
    return lines


def _render_support_table() -> list[str]:
    return [
        "description=[table]",
        "description=[tr]",
        "description=[td][i]MADE FOR:[/i] [b]NEW MUSIC [42+][/b][/td]",
        "description=[td][i]GENERATED BY:[/i] [b]NEW MUSIC BUILDER[/b][/td]",
        "description=[/tr]",
        "description=[tr]",
        f"description=[td][url={NEW_MUSIC_WORKSHOP_URL}][img]{NEW_MUSIC_WORKSHOP_IMAGE}[/img][/url][/td]",
        f"description=[td][url={NEW_MUSIC_BUILDER_WORKSHOP_URL}][img]{NEW_MUSIC_BUILDER_WORKSHOP_IMAGE}[/img][/url][/td]",
        "description=[/tr]",
        "description=[/table]",
    ]


def _render_mode_legend(plan: ExportPlan) -> list[str]:
    if not _has_mixed_modes(plan):
        return []
    lines = ["description=[quote]"]
    lines.append("description=%s" % t("[b]Singles[/b]: Each song is its own item."))
    lines.append("description=%s" % t("[b]Mixtape[/b]: Dynamic playlist on one item."))
    lines.extend(["description=[/quote]", "description="])
    return lines


def _has_mixed_modes(plan: ExportPlan) -> bool:
    has_singles = any(row.row_mode == "singles" for row in plan.rows)
    has_mixtapes = any(row.row_mode == "mixtape" for row in plan.rows)
    return has_singles and has_mixtapes


def _ordered_sides(row: PlannedMediaRow) -> list[PlannedSide]:
    return sorted(row.sides, key=lambda side: 0 if side.side == "A" else 1)


def _ordered_workshop_tables(
    project: ProjectConfig,
    plan: ExportPlan,
    *,
    mixed_modes: bool,
) -> list[tuple[str | None, list[tuple[str, list[PlannedTrack]]]]]:
    rows_by_source_id: dict[int, list[PlannedMediaRow]] = {}
    for planned_row in plan.rows:
        rows_by_source_id.setdefault(planned_row.source_row_id, []).append(planned_row)

    tables: list[tuple[str | None, list[tuple[str, list[PlannedTrack]]]]] = []
    for source_row in project.media_rows:
        source_rows = rows_by_source_id.get(source_row.row_id, [])
        if not source_rows:
            continue
        if source_rows[0].row_mode == "singles":
            tables.append((None, _singles_workshop_sections(source_rows, mixed_modes=mixed_modes)))
            continue
        for planned_row in sorted(source_rows, key=lambda row: row.row_id):
            tables.append((_escape_workshop_text(planned_row.media_name), _row_workshop_sections(planned_row, mixed_modes=mixed_modes)))
    return tables


def _singles_workshop_sections(rows: list[PlannedMediaRow], *, mixed_modes: bool) -> list[tuple[str, list[PlannedTrack]]]:
    ordered_rows = sorted(rows, key=lambda row: row.row_id)
    tracks = [track for row in ordered_rows for side in _ordered_sides(row) for track in side.tracks]
    section_label = t("[b]Singles[/b]") if mixed_modes else t("[b]Singles[/b] [i]Single Item[/i]")
    return [(section_label, tracks)]


def _row_workshop_sections(row: PlannedMediaRow, *, mixed_modes: bool) -> list[tuple[str, list[PlannedTrack]]]:
    sides = _ordered_sides(row)
    mode_label = t("[b]Singles[/b]") if row.row_mode == "singles" else t("[b]Mixtape[/b]")
    if not _row_has_split_media(row):
        if mixed_modes:
            section_label = mode_label
        else:
            section_label = f"{mode_label} {t('[i]Single Item[/i]')}" if row.row_mode == "singles" else f"{mode_label} {t('[b]Full Album[/b]')}"
        return [(section_label, [track for side in sides for track in side.tracks])]
    return [(f"{mode_label} [b]{t('Side')} {side.side}[/b]", list(side.tracks)) for side in sides]


def _row_has_split_media(row: PlannedMediaRow) -> bool:
    if len(row.sides) <= 1:
        return False
    return any(
        row.enabled_media.get(kind, False) and row.media_modes.get(kind, "single" if kind == "cd" else "split") == "split"
        for kind in ("cassette", "vinyl", "cd")
    )


def _render_track_table(
    title: str | None,
    section_label: str,
    tracks: list[PlannedTrack],
    *,
    current_chars: int = 0,
    reserved_chars: int = 0,
) -> list[str]:
    lines = ["description=[table]"]
    if title:
        lines.append(f"description=[tr][th]{title}[/th][/tr]")
    lines.append(f"description=[tr][td]{section_label}[/td][/tr]")
    omitted_count = 0
    for index, track in enumerate(tracks, start=1):
        candidate = f"description=[tr][td]{index:02d} {_escape_workshop_text(track.display_label)}[/td][/tr]"
        remaining_count = len(tracks) - index
        summary_line = t(
            "description=[tr][td][i]... plus {remaining_count} more song{suffix} in this section.[/i][/td][/tr]"
        ).format(remaining_count=remaining_count, suffix='' if remaining_count == 1 else 's')
        candidate_total = current_chars + _line_char_count(lines + [candidate, "description=[/table]"]) + reserved_chars
        summary_total = current_chars + _line_char_count(lines + [summary_line, "description=[/table]"]) + reserved_chars
        if candidate_total <= WORKSHOP_TOTAL_CHAR_BUDGET:
            lines.append(candidate)
            continue
        if index <= WORKSHOP_MIN_TRACK_ROWS_PER_TABLE and summary_total > WORKSHOP_TOTAL_CHAR_BUDGET:
            lines.append(candidate)
            continue
        omitted_count = remaining_count + 1
        break
    if omitted_count:
        lines.append(
            t(
                "description=[tr][td][i]... plus {omitted_count} more song{suffix} in this section.[/i][/td][/tr]"
            ).format(omitted_count=omitted_count, suffix='' if omitted_count == 1 else 's')
        )
    lines.append("description=[/table]")
    return lines


def _line_char_count(lines: list[str]) -> int:
    return sum(len(line) + 1 for line in lines)


def _escape_workshop_text(value: str) -> str:
    return value.replace("[", "(").replace("]", ")")
